In [27]:
import numpy as np
import sys as sys

def init_cd(n: int)-> np.ndarray:
    lst = n * [-1]
    arr = np.array(lst)
    return arr
init_cd(5)

array([-1, -1, -1, -1, -1])

In [28]:
def find(ind: int, p_cd: np.ndarray)-> int:
    z = ind

    while p_cd[z] > -1:
        z = p_cd[z]
        
    while p_cd[ind] >-1:
        y = p_cd[ind]
        p_cd[ind] = z
        ind = y
    return z

In [29]:
def union(rep_1: int, rep_2: int, p_cd: np.ndarray)-> int:
    x = find(rep_1, p_cd)
    y = find(rep_2, p_cd)
        
    if x == y:
            return -1
        
    if p_cd[y] < p_cd[x]:      
        p_cd[x] = y
        rep = y  
    elif p_cd[y] > p_cd[x]:    
        p_cd[y] = x 
        rep = x
    else:
        p_cd[y] = x
        p_cd[x] -= 1
        rep =  x     
    return rep

In [30]:
def cd_2_dict(p_cd: np.ndarray)-> dict:
    d = {}
    for i in range(0, len(p_cd)):
        if p_cd[i] < 0:
            h = []
            j = i
            h.append(j)
            j += 1
            while j < len(p_cd) and p_cd[j] >= 0:
                h.append(j)
                j+=1
            d[i] = h
    return d

def cd_2_dictv2(p_cd: np.ndarray)-> dict:
    d = {}
    i = 0
    while i < len(p_cd):
        if p_cd[i] < 0:
            h = []
            j = i
            h.append(i)
            i += 1
            while i < len(p_cd) and p_cd[i] >= 0:
                h.append(i)
                i+=1
            d[j] = h
    return d

def cd_2_dictv3(p_cd: np.ndarray)-> dict:
    d = {}
    i = 0
    while i < len(p_cd):
        h = []
        j = i
        h.append(i)
        i += 1
        while i < len(p_cd) and p_cd[i] >= 0:
            h.append(i)
            i+=1
        d[j] = h
    return d

def cd_2_dictv4(p_cd: np.ndarray)-> dict:
    d = {}
    for i in range(len(p_cd)):
        if p_cd[i] < 0:
            d[i] = []
        
    for i in range(len(p_cd)):
        aux = find(i, p_cd)
        d[aux].append(i)
    return d
    



d = cd_2_dict([-3, 0, 1, -2, 3, -2, 5])
d2 = cd_2_dictv2([-3, 0, 1, -2, 3, -2, 5])
d3 = cd_2_dictv3([-3, 0, 1, -2, 3, -2, 5])
d4 = cd_2_dictv4([1, -2, 1, -2, 3, -2, 5])

print(d)
print(d2)
print(d3)
print(d4)

{0: [0, 1, 2], 3: [3, 4], 5: [5, 6]}
{0: [0, 1, 2], 3: [3, 4], 5: [5, 6]}
{0: [0, 1, 2], 3: [3, 4], 5: [5, 6]}
{1: [0, 1, 2], 3: [3, 4], 5: [5, 6]}


In [31]:
def ccs(n: int, l: list)-> dict:
    cd = init_cd(n)
    for i in l:
        union(i[0], i[1], cd)
    print(cd)
    d = cd_2_dictv4(cd)
    return d

print(ccs(7, [(0, 1), (0, 3), (1, 2), (1, 4), (3, 4), (4, 5), (4, 6), (5, 6)]))

[-2  0  0  0  0  0  0]
{0: [0, 1, 2, 3, 4, 5, 6]}


In [32]:
def dist_matrix(n_nodes: int, w_max=10)-> np.ndarray:
    m = np.zeros((n_nodes, n_nodes), dtype=int)
    i = 0
    while i < n_nodes:
        j = i
        while j < n_nodes:
            if i != j:
                m[i][j] = np.random.randint(0, w_max+1)
                m[j][i] = m[i][j]
            j+=1
        i+=1
    print(m)
    return(m)

dist_matrix(4, 10)

[[0 0 8 4]
 [0 0 8 6]
 [8 8 0 4]
 [4 6 4 0]]


array([[0, 0, 8, 4],
       [0, 0, 8, 6],
       [8, 8, 0, 4],
       [4, 6, 4, 0]])

In [33]:
def greedy_tsp(dist_m: np.ndarray, node_ini=0)-> list:
    num_nodes = dist_m.shape[0]
    circuit = [node_ini]
    while len(circuit) < num_nodes:
        current_city = circuit[-1]
        options = np.argsort(dist_m[ current_city])
        for i in options:
            if i not in circuit:
                circuit.append(i)
                break
    circuit.append(node_ini)
    return circuit


    
kaka = dist_matrix(4,5)
greedy_tsp(kaka, 1)

    

[[0 4 1 1]
 [4 0 5 1]
 [1 5 0 1]
 [1 1 1 0]]


[1, 3, 0, 2, 1]

In [34]:
def len_circuit(circuit: list, dist_m: np.ndarray)-> int:
    i = 0
    longitud = 0
    while (i < len(circuit) - 1):
        longitud += dist_m[circuit[i]][circuit[i+1]]
        i+=1
    return longitud

len_circuit([2, 3, 0, 1, 2], [[ 0, 1,  9,  1], [1,  0,  10,  6],[9,  10,  0,  2],[1,  6,  2,  0]])

14

In [46]:
def repeated_greedy_tsp(dist_m: np.ndarray)-> list:
    num_nodes = dist_m.shape[0]
    i = 0
    longitud = sys.maxsize
    while i < num_nodes:
        circuit = greedy_tsp(dist_m, i)
        aux = len_circuit(circuit, dist_m)
        print(circuit)
        print(aux)
        if aux < longitud:
            longitud = aux
            circuito = circuit
        i+=1
    return circuito

In [48]:
repeated_greedy_tsp(dist_matrix(9, 10))

[[ 0 10  2  5  7  4  6  8  2]
 [10  0  7 10  0  0  7  5  4]
 [ 2  7  0  1  8  1 10  1  6]
 [ 5 10  1  0  8  5  0  6  3]
 [ 7  0  8  8  0 10  1  4 10]
 [ 4  0  1  5 10  0  8  1  7]
 [ 6  7 10  0  1  8  0  8  6]
 [ 8  5  1  6  4  1  8  0  4]
 [ 2  4  6  3 10  7  6  4  0]]
[0, 2, 3, 6, 4, 1, 5, 7, 8, 0]
11
[1, 4, 6, 3, 2, 5, 7, 8, 0, 1]
20
[2, 3, 6, 4, 1, 5, 7, 8, 0, 2]
11
[3, 6, 4, 1, 5, 2, 7, 8, 0, 3]
14
[4, 1, 5, 2, 3, 6, 0, 8, 7, 4]
18
[5, 1, 4, 6, 3, 2, 7, 8, 0, 5]
13
[6, 3, 2, 5, 1, 4, 7, 8, 0, 6]
18
[7, 2, 3, 6, 4, 1, 5, 0, 8, 7]
13
[8, 0, 2, 3, 6, 4, 1, 5, 7, 8]
11


[0, 2, 3, 6, 4, 1, 5, 7, 8, 0]